apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placementbinding-crossplane-eks-lb-sa
  namespace: crossplane-system
placementRef:
  name: eks-placementrule
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-crossplane-eks-lb-sa
    apiGroup: policy.open-cluster-management.io
    kind: Policy