apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: demo3
    apps.open-cluster-management.io/git-path: crossplane/crossplane-resources/aws/manifests/overlays/region-us-east-1
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: crossplane-aws-resources
  name: aws-subscription-east-1
spec:
  channel: channel-rhacm-git-ns/rhacm-git
  placement:
    placementRef:
      kind: PlacementRule
      name: hub-placementrule
