apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: crossplane/crossplane-resources/aws/manifests/overlays/region-us-east-1
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: crossplane-aws-resources
  name: crossplane-aws-resources-subscription-east-1
spec:
  channel: channel-git-crossplane/git-crossplane
  placement:
    placementRef:
      kind: PlacementRule
      name: hub-placementrule
