apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: policy-xks-acs-policypullsecret
  namespace: stackrox
spec:
  namespaceSelector:
    exclude:
    - kube-*
    include:
    - default
  object-templates:
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      data:
        .dockerconfigjson: '{{ fromSecret "open-cluster-management-agent" "open-cluster-management-image-pull-credentials" ".dockerconfigjson" }}'
      kind: Secret
      metadata:
        name: pull-secret
        namespace: stackrox
      type: Opaque
  remediationAction: enforce
  severity: low
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-xks-acs-placementbinding
  namespace: stackrox
placementRef:
  name: non-openshift-placementrule
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-xks-acs-policypullsecret
    apiGroup: policy.open-cluster-management.io
    kind: Policy