kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:privileged:crossplane-accounts'
subjects:
  - kind: ServiceAccount
    name: crossplane
    namespace: crossplane-system
  - kind: ServiceAccount
    name: rbac-manager
    namespace: crossplane-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
