kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crossplane-install-clusterole
  labels:
    app: crossplane
rules:
  - verbs:
      - '*'
    apiGroups:
      - acm.aws.crossplane.io
      - acmpca.aws.crossplane.io
      - apigateway.aws.crossplane.io
      - apigatewayv2.aws.crossplane.io
      - athena.aws.crossplane.io
      - aws.crossplane.io
      - cache.aws.crossplane.io
      - cloudfront.aws.crossplane.io
      - cloudsearch.aws.crossplane.io
      - cloudwatchlogs.aws.crossplane.io
      - cognitoidentity.aws.crossplane.io
      - cognitoidentityprovider.aws.crossplane.io
      - database.aws.crossplane.io
      - dax.aws.crossplane.io
      - docdb.aws.crossplane.io
      - dynamodb.aws.crossplane.io
      - ec2.aws.crossplane.io
      - ecr.aws.crossplane.io
      - ecs.aws.crossplane.io
      - efs.aws.crossplane.io
      - eks.aws.crossplane.io
      - elasticache.aws.crossplane.io
      - elasticloadbalancing.aws.crossplane.io
      - elbv2.aws.crossplane.io
      - glue.aws.crossplane.io
      - iam.aws.crossplane.io
      - iot.aws.crossplane.io
      - kafka.aws.crossplane.io
      - kinesis.aws.crossplane.io
      - kms.aws.crossplane.io
      - lambda.aws.crossplane.io
      - mq.aws.crossplane.io
      - mwaa.aws.crossplane.io
      - neptune.aws.crossplane.io
      - opensearchservice.aws.crossplane.io
      - prometheusservice.aws.crossplane.io
      - ram.aws.crossplane.io
      - rds.aws.crossplane.io
      - redshift.aws.crossplane.io
      - route53.aws.crossplane.io
      - route53resolver.aws.crossplane.io
      - s3.aws.crossplane.io
      - secretsmanager.aws.crossplane.io
      - servicediscovery.aws.crossplane.io
      - sfn.aws.crossplane.io
      - sns.aws.crossplane.io
      - sqs.aws.crossplane.io
      - transfer.aws.crossplane.io
      - azure.crossplane.io
      - cache.azure.crossplane.io
      - compute.azure.crossplane.io
      - database.azure.crossplane.io
      - dns.azure.crossplane.io
      - keyvault.azure.crossplane.io
      - network.azure.crossplane.io
      - storage.azure.crossplane.io
      - cache.gcp.crossplane.io
      - compute.gcp.crossplane.io
      - container.gcp.crossplane.io
      - database.gcp.crossplane.io
      - dns.gcp.crossplane.io
      - gcp.crossplane.io
      - gcp.secrets.crossplane.io
      - iam.gcp.crossplane.io
      - kms.gcp.crossplane.io
      - pubsub.gcp.crossplane.io
      - registry.gcp.crossplane.io
      - servicenetworking.gcp.crossplane.io
      - storage.gcp.crossplane.io
    resources:
      - '*'