kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crossplane-install-clusterole
  labels:
    app: crossplane
rules:
  - verbs:
      - '*'
    apiGroups:
      - acm.aws.crossplane.io
      - acmpca.aws.crossplane.io
      - apigateway.aws.crossplane.io
      - apigatewayv2.aws.crossplane.io
      - athena.aws.crossplane.io
      - aws.crossplane.io
      - cache.aws.crossplane.io
      - cloudfront.aws.crossplane.io
      - cloudsearch.aws.crossplane.io
      - cloudwatchlogs.aws.crossplane.io
      - cognitoidentity.aws.crossplane.io
      - cognitoidentityprovider.aws.crossplane.io
      - database.aws.crossplane.io
      - dax.aws.crossplane.io
      - docdb.aws.crossplane.io
      - dynamodb.aws.crossplane.io
      - ec2.aws.crossplane.io
      - ecr.aws.crossplane.io
      - ecs.aws.crossplane.io
      - efs.aws.crossplane.io
      - eks.aws.crossplane.io
      - elasticache.aws.crossplane.io
      - elasticloadbalancing.aws.crossplane.io
      - elbv2.aws.crossplane.io
      - glue.aws.crossplane.io
      - iam.aws.crossplane.io
      - iot.aws.crossplane.io
      - kafka.aws.crossplane.io
      - kinesis.aws.crossplane.io
      - kms.aws.crossplane.io
      - lambda.aws.crossplane.io
      - mq.aws.crossplane.io
      - mwaa.aws.crossplane.io
      - neptune.aws.crossplane.io
      - opensearchservice.aws.crossplane.io
      - prometheusservice.aws.crossplane.io
      - ram.aws.crossplane.io
      - rds.aws.crossplane.io
      - redshift.aws.crossplane.io
      - route53.aws.crossplane.io
      - route53resolver.aws.crossplane.io
      - s3.aws.crossplane.io
      - secretsmanager.aws.crossplane.io
      - servicediscovery.aws.crossplane.io
      - sfn.aws.crossplane.io
      - sns.aws.crossplane.io
      - snstopics.notification.aws.crossplane.io
      - snssubscriptions.notification.aws.crossplane.io
      - sqs.aws.crossplane.io
      - transfer.aws.crossplane.io
      - azure.crossplane.io
      - cache.azure.crossplane.io
      - compute.azure.crossplane.io
      - database.azure.crossplane.io
      - dns.azure.crossplane.io
      - keyvault.azure.crossplane.io
      - network.azure.crossplane.io
      - storage.azure.crossplane.io
      - cache.gcp.crossplane.io
      - compute.gcp.crossplane.io
      - container.gcp.crossplane.io
      - database.gcp.crossplane.io
      - dns.gcp.crossplane.io
      - gcp.crossplane.io
      - gcp.secrets.crossplane.io
      - iam.gcp.crossplane.io
      - kms.gcp.crossplane.io
      - pubsub.gcp.crossplane.io
      - registry.gcp.crossplane.io
      - servicenetworking.gcp.crossplane.io
      - storage.gcp.crossplane.io
      - xrds
      - apiextensions.crossplane.io
      - rrs
      - oidcprovider
      - iamrole
      - kvsecret
      - notification.aws.crossplane.io
      - pkg.crossplane.io
      - secrets.crossplane.io
      - serviceaccountkeys.iam.gcp.crossplane.io
      - providerconfigs.gcp.crossplane.io
      - providerconfigusages.gcp.crossplane.io
      - cloudmemorystoreinstances.cache.gcp.crossplane.io
      - cryptokeys.kms.gcp.crossplane.io
      - serviceaccounts.iam.gcp.crossplane.io
      - containerregistries.registry.gcp.crossplane.io
      - keyrings.kms.gcp.crossplane.io
      - buckets.storage.gcp.crossplane.io
      - subnetworks.compute.gcp.crossplane.io
      - globaladdresses.compute.gcp.crossplane.io
      - addresses.compute.gcp.crossplane.io
      - networks.compute.gcp.crossplane.io
      - routers.compute.gcp.crossplane.io
      - cloudsqlinstances.database.gcp.crossplane.io
      - clusters.container.gcp.crossplane.io
      - policies.dns.gcp.crossplane.io
      - firewalls.compute.gcp.crossplane.io
      - nodepools.container.gcp.crossplane.io
      - resourcerecordsets.dns.gcp.crossplane.io
      - serviceaccountpolicies.iam.gcp.crossplane.io
      - subscriptions.pubsub.gcp.crossplane.io
      - cryptokeypolicies.kms.gcp.crossplane.io
      - connections.servicenetworking.gcp.crossplane.io
      - topics.pubsub.gcp.crossplane.io
      - bucketpolicies.storage.gcp.crossplane.io
      - bucketpolicymembers.storage.gcp.crossplane.io
      - serviceaccountkey.iam.gcp.crossplane.io
      - grouppolicyattachments.iam.aws.crossplane.io
      - dbsubnetgroups.database.aws.crossplane.io
      - repositorypolicies.ecr.aws.crossplane.io
      - topics.sns.aws.crossplane.io
      - rdsinstances.database.aws.crossplane.io
      - services.ecs.aws.crossplane.io
      - certificateauthorities.acmpca.aws.crossplane.io
      - cacheparametergroups.elasticache.aws.crossplane.io
      - userpools.cognitoidentityprovider.aws.crossplane.io
      - groupusermemberships.cognitoidentityprovider.aws.crossplane.io
      - groups.cognitoidentityprovider.aws.crossplane.io
      - alertmanagerdefinitions.prometheusservice.aws.crossplane.io
      - addons.eks.aws.crossplane.io
      - users.transfer.aws.crossplane.io
      - servers.transfer.aws.crossplane.io
      - users.mq.aws.crossplane.io
      - cloudfrontoriginaccessidentities.cloudfront.aws.crossplane.io
      - dbinstanceroleassociations.rds.aws.crossplane.io
      - functions.lambda.aws.crossplane.io
      - configurations.kafka.aws.crossplane.io
      - groupusermemberships.iam.aws.crossplane.io
      - policies.iam.aws.crossplane.io
      - domains.cloudsearch.aws.crossplane.io
      - replicationgroups.cache.aws.crossplane.io
      - identityproviderconfigs.eks.aws.crossplane.io
      - cacheclusters.cache.aws.crossplane.io
      - cachesubnetgroups.cache.aws.crossplane.io
      - taskdefinitions.ecs.aws.crossplane.io
      - dbclusters.docdb.aws.crossplane.io
      - dbsubnetgroups.docdb.aws.crossplane.io
      - parametergroups.dax.aws.crossplane.io
      - clusters.dax.aws.crossplane.io
      - dbclusterparametergroups.docdb.aws.crossplane.io
      - nodegroups.eks.aws.crossplane.io
      - subnetgroups.dax.aws.crossplane.io
      - dbinstances.docdb.aws.crossplane.io
      - clusters.ecs.aws.crossplane.io
      - users.iam.aws.crossplane.io
      - instanceprofiles.iam.aws.crossplane.io
      - userpolicyattachments.iam.aws.crossplane.io
      - elbattachments.elasticloadbalancing.aws.crossplane.io
      - groups.iam.aws.crossplane.io
      - clusters.eks.aws.crossplane.io
      - elbs.elasticloadbalancing.aws.crossplane.io
      - rolepolicyattachments.iam.aws.crossplane.io
      - accesskeys.iam.aws.crossplane.io
      - roles.iam.aws.crossplane.io
      - queues.sqs.aws.crossplane.io
      - certificates.acm.aws.crossplane.io
      - repositories.ecr.aws.crossplane.io
      - certificateauthoritypermissions.acmpca.aws.crossplane.io
      - secrets.secretsmanager.aws.crossplane.io
      - subscriptions.sns.aws.crossplane.io
      - clusters.redshift.aws.crossplane.io
      - lifecyclepolicies.ecr.aws.crossplane.io
      - resourceshares.ram.aws.crossplane.io
      - fargateprofiles.eks.aws.crossplane.io
      - resources.apigateway.aws.crossplane.io
      - jobs.glue.aws.crossplane.io
      - statemachines.sfn.aws.crossplane.io
      - streams.kinesis.aws.crossplane.io
      - clusters.kafka.aws.crossplane.io
      - workgroups.athena.aws.crossplane.io
      - things.iot.aws.crossplane.io
      - dbclusterparametergroups.rds.aws.crossplane.io
      - httpnamespaces.servicediscovery.aws.crossplane.io
      - openidconnectproviders.iam.aws.crossplane.io
      - dbparametergroups.rds.aws.crossplane.io
      - resourceservers.cognitoidentityprovider.aws.crossplane.io
      - responseheaderspolicies.cloudfront.aws.crossplane.io
      - dbclusters.neptune.aws.crossplane.io
      - permissions.lambda.aws.crossplane.io
      - cachepolicies.cloudfront.aws.crossplane.io
      - identityproviders.cognitoidentityprovider.aws.crossplane.io
      - connections.glue.aws.crossplane.io
      - userpooldomains.cognitoidentityprovider.aws.crossplane.io
      - globalclusters.rds.aws.crossplane.io
      - policies.iot.aws.crossplane.io
      - privatednsnamespaces.servicediscovery.aws.crossplane.io
      - crawlers.glue.aws.crossplane.io
      - distributions.cloudfront.aws.crossplane.io
      - identitypools.cognitoidentity.aws.crossplane.io
      - keys.kms.aws.crossplane.io
      - methods.apigateway.aws.crossplane.io
      - tables.dynamodb.aws.crossplane.io
      - backups.dynamodb.aws.crossplane.io
      - globaltables.dynamodb.aws.crossplane.io
      - accesspoints.efs.aws.crossplane.io
      - dbinstances.rds.aws.crossplane.io
      - securityconfigurations.glue.aws.crossplane.io
      - activities.sfn.aws.crossplane.io
      - dbclusters.rds.aws.crossplane.io
      - aliases.kms.aws.crossplane.io
      - publicdnsnamespaces.servicediscovery.aws.crossplane.io
      - userpoolclients.cognitoidentityprovider.aws.crossplane.io
      - filesystems.efs.aws.crossplane.io
      - mounttargets.efs.aws.crossplane.io
      - databases.glue.aws.crossplane.io
      - classifiers.glue.aws.crossplane.io
      - restapis.apigateway.aws.crossplane.io
      - loggroups.cloudwatchlogs.aws.crossplane.io
      - domains.opensearchservice.aws.crossplane.io
      - rulegroupsnamespaces.prometheusservice.aws.crossplane.io
      - environments.mwaa.aws.crossplane.io
      - workspaces.prometheusservice.aws.crossplane.io
      - brokers.mq.aws.crossplane.io
      - aws.crossplane.io
      - resolver.aws.crossplane.io
      - providerconfigs.aws.crossplane.io
      - providerconfigusages.aws.crossplane.io
      - resourcegroups.azure.crossplane.io
      - providerconfigusages.azure.crossplane.io
      - providerconfigs.azure.crossplane.io
    resources:
      - '*'