apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations: {}
  labels:
    app: crossplane
  name: crossplane-install-subscription
  namespace: crossplane-system
spec:
  channel: channel-helm-crossplane/helm-crossplane
  name: crossplane
  packageOverrides:
  - packageAlias: crossplane-stable
    packageName: crossplane
    packageOverrides:
    - path: spec
      value:
      # Update Values in Helm values.yaml file
        replicas: 2
        provider:
          packages:
          - provider-aws
          - provider-gcp
          - provider-azure
        serviceAccount:
          customAnnotations: 
            deployed.via.acm.subscription: crossplane-install-subscription
        customAnnotations: 
          deployed.via.acm.subscription: crossplane-install-subscription
  placement:
    placementRef:
      kind: PlacementRule
      name: hub-placementrule