bases:
#EKS Base Cluster Files
#- ../../eks-cluster-base
#ACM Attach Cluster Files
- ../../policy-acm-cluster-attach-base
patches:
- path: ./patches/cluster-patch.yaml
  target:
    kind: Cluster
- path: ./patches/nodegroup-patch.yaml
  target:
    kind: NodeGroup
patchesJson6902:
  - target:
      group: eks.aws.crossplane.io
      version: v1beta1
      kind: Cluster
      name: base-cluster-name
    path: ./patches/cluster-rename-patch.yaml
  - target:
      group: eks.aws.crossplane.io
      version: v1alpha1
      kind: NodeGroup
      name: base-cluster-nodegroup
    path: ./patches/nodegroup-rename-patch.yaml
  - target:
      group: batch
      version: v1
      kind: Job
      name: until-cluster-ready
    path: ./patches/job-patch.yaml
  - target:
      group: policy.open-cluster-management.io
      version: v1
      kind: Policy
      name: policy-replace-me
    path: ./patches/policy-patch.yaml
  - target:
      group: policy.open-cluster-management.io
      version: v1
      kind: PlacementBinding
      name: pb-replace-me
    path: ./patches/pb-patch.yaml