bases:
- ../../eks-cluster-base
patches:
- path: ./patches/cluster-patch.yaml
  target:
    kind: Cluster
patchesJson6902:
  - target:
      group: eks.aws.crossplane.io
      version: v1beta1
      kind: Cluster
      name: base-cluster-name
    path: ./patches/cluster-rename-patch.yaml