apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: hub-placementrule
  namespace: global-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - local-cluster
      - key: vendor
        operator: In
        values:
          - OpenShift