apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: crossplane-eks-cluster1-nodegroup
spec:
  forProvider:
    region: us-east-1
    clusterNameRef:
      name: crossplane-eks-cluster1
    # Defined in crossplane-resources/aws/manifests
    subnetRefs:
      - name: crossplane-subnet-1-us-east-1
      - name: crossplane-subnet-2-us-east-1
      - name: crossplane-subnet-3-us-east-1
    scalingConfig:
      desiredSize: 1
      maxSize: 1
      minSize: 1

