kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'open-cluster-management:subscription-admin'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'open-cluster-management:subscription-admin'
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: '{{hub (index (lookup "v1" "Namespace" "" "global-policies").metadata.annotations "openshift.io/requester") hub}}'