apiVersion: externaldns.olm.openshift.io/v1beta1
kind: ExternalDNS
metadata:
  name: aws-certman
spec:
  domains:
    - filterType: Include
      matchType: Exact
      name: test.oyegunle.com
  provider:
    type: AWS
  source:
    type: Service 
    service:
      serviceType:
        - ExternalName
    labelFilter: 
      matchLabels:
        external-dns.mydomain.org/publish: "yes"
    hostnameAnnotation: "Allow" 
    fqdnTemplate:
    - "{{.Name}}.clustertest.test.oyegunle.com" 