apiVersion: network.azure.crossplane.io/v1alpha3
kind: Subnet
metadata:
  name: crossplane-azure-sub
spec:
  properties:
    addressPrefix: 10.240.0.0/16
    serviceEndpoints:
      - service: Microsoft.Sql
  providerConfigRef:
    name: provider-azure