apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: demo2
    apps.open-cluster-management.io/git-path: crossplane/crossplane-clusters/manifests/eks-cluster-overlays/crossplane-eks-cluster1/acm-attach/  
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: crossplane-clusters
  name: crossplane-cluster-eks-cluster-1-attach
  namespace: crossplane-system
spec:
  allow:
  - apiVersion: policy.open-cluster-management.io/v1
    kinds:
    - Policy
  - apiVersion: policy.open-cluster-management.io/v1
    kinds:
    - PlacementBinding
  - apiVersion: batch/v1
    kinds:
    - Job 
  channel: channel-git-crossplane/git-crossplane
  placement:
    placementRef:
      kind: PlacementRule
      name: hub-placementrule
