bases:
- ../../base
namespace: crossplane-system
patches:
- path: ./patches/patch-vpc.yaml
  target:
    kind: VPC
- path: ./patches/patch-subnet1.yaml
  target:
    kind: Subnet
    name: crossplane-subnet-1
- path: ./patches/patch-subnet2.yaml
  target:
    kind: Subnet
    name: crossplane-subnet-2
- path: ./patches/patch-subnet3.yaml
  target:
    kind: Subnet
    name: crossplane-subnet-3
- path: ./patches/patch-sg.yaml
  target:
    kind: SecurityGroup
    name: crossplane-eks-sg
- path: ./patches/patch-ig.yaml
  target:
    kind: InternetGateway
    name: crossplane-ig
- path: ./patches/patch-rt-1.yaml
  target:
    kind: RouteTable
    name: crossplane-routetable-1
- path: ./patches/patch-rt-2.yaml
  target:
    kind: RouteTable
    name: crossplane-routetable-2
- path: ./patches/patch-rt-3.yaml
  target:
    kind: RouteTable
    name: crossplane-routetable-3
#Very possible to merge both patch methods into one but couldnt be bothered..lol
patchesJson6902:
  - target:
      group: ec2.aws.crossplane.io
      version: v1beta1
      kind: SecurityGroup
      name: crossplane-eks-sg
    path: ./patches/patch-sg-rename.yaml
  - target:
      group: ec2.aws.crossplane.io
      version: v1beta1
      kind: Subnet
      name: crossplane-subnet-1
    path: ./patches/patch-subnet1-rename.yaml
  - target:
      group: ec2.aws.crossplane.io
      version: v1beta1
      kind: Subnet
      name: crossplane-subnet-2
    path: ./patches/patch-subnet2-rename.yaml
  - target:
      group: ec2.aws.crossplane.io
      version: v1beta1
      kind: Subnet
      name: crossplane-subnet-3
    path: ./patches/patch-subnet3-rename.yaml
  - target:
      group: ec2.aws.crossplane.io
      version: v1beta1
      kind: VPC
      name: crossplane-vpc
    path: ./patches/patch-vpc-rename.yaml
  - target:
      group: ec2.aws.crossplane.io
      version: v1beta1
      kind: InternetGateway
      name: crossplane-ig
    path: ./patches/patch-ig-rename.yaml
  - target:
      group: ec2.aws.crossplane.io
      version: v1beta1
      kind: RouteTable
      name: crossplane-routetable-1
    path: ./patches/patch-rt-rename-1.yaml
  - target:
      group: ec2.aws.crossplane.io
      version: v1beta1
      kind: RouteTable
      name: crossplane-routetable-2
    path: ./patches/patch-rt-rename-2.yaml
  - target:
      group: ec2.aws.crossplane.io
      version: v1beta1
      kind: RouteTable
      name: crossplane-routetable-3
    path: ./patches/patch-rt-rename-3.yaml