#Policy Changes
- op: replace
  path: /metadata/name
  value: policy-secret-attach-aks-cluster-1
- op: replace
  path: /spec/policy-templates/0/objectDefinition/metadata/name
  value: policy-secret-attach-aks-cluster-1
#Secret Object Changes
- op: replace
  path: /spec/policy-templates/0/objectDefinition/spec/object-templates/0/objectDefinition/metadata/namespace
  value: aks-cluster-1
- op: replace
  path: /spec/policy-templates/0/objectDefinition/spec/object-templates/0/objectDefinition/data/kubeconfig
  value: '{{ fromSecret "crossplane-system" "aks-cluster-1" "kubeconfig" }}'
#Namespace Changes
- op: replace
  path: /spec/policy-templates/0/objectDefinition/spec/object-templates/1/objectDefinition/metadata/name
  value: aks-cluster-1
