bases:
#AKS Base Cluster Files
- ../../../aks-cluster-base
namespace: crossplane-system
patches:
- path: ./patches/cluster-patch.yaml
  target:
    kind: AKSCluster
    name: crossplane-aks-cluster
patchesJson6902:
  - target:
      group: compute.azure.crossplane.io
      version: v1alpha3
      kind: AKSCluster
      name: crossplane-aks-cluster
    path: ./patches/cluster-rename-patch.yaml
