bases:
- ../../../base/oidc
patches:
  - path: ./patches/patch-policy-crossplane-oidc-provider.yaml
    target:
      kind: Policy
  - path: ./patches/patch-placementbinding-crossplane-oidc-provider.yaml
    target:
      kind: PlacementBinding
patchesJson6902:
  - target:
      group: policy.open-cluster-management.io
      version: v1
      kind: Policy
      name: policy-crossplane-eks-oidc-provider
    path: ./patches/patch-policy-crossplane-oidc-provider-rename.yaml
  - target:
      group: policy.open-cluster-management.io
      version: v1
      kind: PlacementBinding
      name: placementbinding-crossplane-eks-oidc-provider
    path: ./patches/patch-placementbinding-crossplane-oidc-provider-rename.yaml