apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-openshift-operators
placementBindingDefaults:
  name: openshift-operators-pb
policyDefaults:
  namespace: global-policies
  # Use an existing placement rule so that placement bindings can be consolidated
  placement:
    placementRulePath: ../placementrules/OCP/ocp-placementrule.yaml
  remediationAction: enforce
  severity: medium
policies:
  - name: policy-ocp-gitops-operator
    manifests:
      - path: openshift-gitops-subscription.yaml
  - name: policy-ocp-pipelines-operator
    manifests:
      - path: openshift-pipelines-subscription.yaml