apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    custom: olm-policies
  name: non-openshift-placementrule
  namespace: global-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - AKS
          - EKS
          - GKS