apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations: {}    
  labels:
    app: nginx-controller
  name: nginx-subscription
  namespace: global-policies
spec:
  channel: namespace-helm-ingress-nginx/channel-helm-ingress-nginx
  name: ingress-nginx
  packageOverrides:
  - packageName: ingress-nginx
    packageAlias: ingress-nginx
    packageOverrides:
    - path: spec
      value:
        controller.replicaCount: "1"
        controller.setAsDefaultIngress: true
  packageFilter:
    version: "4.2.5"
