apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: base-cluster-name
  labels:
    app: "crossplane"
    provider: aws
spec:
  forProvider:
    # Defined in ../../crossplane-resources/aws/manifests
    roleArnRef:
      name: crossplane-iam-node-role
    resourcesVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: true
  providerConfigRef:
    name: provider-aws