apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: base-cluster-name
  labels:
    app: "crossplane"
    provider: aws
spec:
  forProvider:
    region: us-east-1
    # Defined in ../../crossplane-resources/aws/manifests
    roleArnRef:
      name: crossplane-iam-role
    resourcesVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: true
      # Defined in ../../crossplane-resources/aws/manifests
      subnetIdRefs:
        - name: crossplane-subnet-1
        - name: crossplane-subnet-2
      securityGroupIdRefs:
        - name: crossplane-eks-sg
  providerConfigRef:
    name: provider-aws