apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: base-cluster-nodegroup
  labels:
    app: "crossplane"
    provider: aws
spec:
  forProvider:
    nodeRoleRef:
      name: crossplane-iam-node-role
    scalingConfig:
      desiredSize: 1
      maxSize: 1
      minSize: 1
    updateConfig:
      maxUnavailablePercentage: 50
      force: true
  providerConfigRef:
    name: provider-aws