apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-xks-olm
placementBindingDefaults:
  name: xks-olm-binding
policyDefaults:
  placement:
    placementRuleName: non-openshift-placementrule
  controls:
    - "CM-2 Baseline Configuration"
  pruneObjectBehavior: "DeleteIfCreated"
  namespace: global-policies
  remediationAction: enforce
  severity: medium
policies:
- name: policy-xks-olm-crds
  disabled: false
  manifests:
    - path: ./crds
- name: policy-xks-olm-deploy
  disabled: false
  manifests:
    - path: ./olm_deploy
  remediationAction: enforce
