apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: nginx
  namespace: ingress-basic
  annotations:
    controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path": "/healthz"
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - nginx