apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path": "/healthz"
    controller.replicaCount: "2"
  labels:
    app: nginx
  name: nginx-subscription-1
  namespace: ingress-basic
spec:
  channel: global-policies/helm-nginx
  name: ingress-nginx
  packageOverrides:
  - packageName: ingress-nginx
    packageAlias: ingress-nginx
  packageFilter:
    version: "4.2.5"
  placement:
    placementRef:
      kind: PlacementRule
      name: nginx-aks-placement