#source: https://github.com/nasx/umbrella-gitops/blob/main/manifests/advanced-cluster-management-policies/acs/securedcluster/securedcluster.yaml
apiVersion: v1
kind: Secret
metadata:
  name: admission-control-tls
  namespace: stackrox
data:
  ca.pem: |
    {{hub (index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "ca.pem") | protect hub}}
  admission-control-cert.pem: |
    {{hub (index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "admission-control-cert.pem") | protect hub}}
  admission-control-key.pem: |
    {{hub (index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "admission-control-key.pem") | protect hub}}
