#source: https://github.com/nasx/umbrella-gitops/blob/main/manifests/advanced-cluster-management-policies/acs/securedcluster/securedcluster.yaml
apiVersion: v1
data:
  ca.pem: '{{hub fromSecret "stackrox" "sensor-tls" "ca.pem" hub}}'
  sensor-cert.pem: '{{hub fromSecret "stackrox" "sensor-tls" "sensor-cert.pem" hub}}'
  sensor-key.pem: '{{hub fromSecret "stackrox" "sensor-tls" "sensor-key.pem" hub}}'
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: '{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").metadata.annotations "init-bundle.stackrox.io/created-at" hub}}'
    init-bundle.stackrox.io/expires-at: '{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").metadata.annotations "init-bundle.stackrox.io/expires-at" hub}}'
    init-bundle.stackrox.io/id: '{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").metadata.annotations "init-bundle.stackrox.io/id" hub}}'
    init-bundle.stackrox.io/name: '{{hub index (lookup "v1" "Secret" "stackrox" "sensor-tls").metadata.annotations "init-bundle.stackrox.io/name" hub}}'
  name: sensor-tls
  namespace: stackrox
type: Opaque