apiVersion: v1
kind: Secret
metadata:
  name: sensor-tls
  namespace: stackrox
data:
  ca.pem: |
    {{hub (index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "ca.pem") | protect hub}}
  sensor-cert.pem: |
    {{hub (index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "sensor-cert.pem") | protect hub}}
  sensor-key.pem: |
    {{hub (index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "sensor-key.pem") | protect hub}}