#source: https://github.com/nasx/umbrella-gitops/blob/main/manifests/advanced-cluster-management-policies/acs/securedcluster/securedcluster.yaml
apiVersion: v1
data:
  ca.pem: '{{hub fromSecret "stackrox" "collector-tls" "ca.pem" hub}}'
  collector-cert.pem: '{{hub fromSecret "stackrox" "collector-tls" "collector-cert.pem" hub}}'
  collector-key.pem: '{{hub fromSecret "stackrox" "collector-tls" "collector-key.pem" hub}}'
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: '{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").metadata.annotations "init-bundle.stackrox.io/created-at" hub}}'
    init-bundle.stackrox.io/expires-at: '{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").metadata.annotations "init-bundle.stackrox.io/expires-at" hub}}'
    init-bundle.stackrox.io/id: '{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").metadata.annotations "init-bundle.stackrox.io/id" hub}}'
    init-bundle.stackrox.io/name: '{{hub index (lookup "v1" "Secret" "stackrox" "collector-tls").metadata.annotations "init-bundle.stackrox.io/name" hub}}'
  name: collector-tls
  namespace: stackrox
type: Opaque