apiVersion: v1
kind: Secret
metadata:
  name: collector-tls
  namespace: stackrox
data:
  ca.pem: |
    {{hub (index (lookup "v1" "Secret" "stackrox" "collector-tls").data "ca.pem") | protect hub}}
  collector-cert.pem: |
    {{hub (index (lookup "v1" "Secret" "stackrox" "collector-tls").data "collector-cert.pem") | protect hub}}
  collector-key.pem: |
    {{hub (index (lookup "v1" "Secret" "stackrox" "collector-tls").data "collector-key.pem") | protect hub}}