apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policygeneratorbaseconfig
placementBindingDefaults:
  name: global-baseconfig
policyDefaults:
  controls:
    - "CM-2 Baseline Configuration"
  pruneObjectBehavior: "DeleteIfCreated"
  remediationAction: enforce
  severity: medium
  namespace: global-policies
  orderPolicies: true
policies:
- name: policy-globalpolicy-namespace
  disabled: false
  manifests:
    - path: ./manifests-namespace
  policySets:
    - policy-global-all-base
- name: policy-placementrules
  disabled: false
  manifests:
    - path: ./manifests-placementrules
  policySets:
    - policy-global-hub
#Hub lookup for namespaced objects no longer supported
# - name: policy-subscription-admin
#   disabled: false
#   manifests:
#     - path: ./manifests-rbac
#   placement:
#     clusterSelectors:
#       name: local-cluster
policySets:
  - name: policy-global-hub
    placement:
      placementRuleName: "bootstrap-hub-placementrule"
  - name: policy-global-all-base
    placement:
      clusterSelectors: {}