apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policygeneratorbaseconfig
placementBindingDefaults:
  name: global-baseconfig
policyDefaults:
  controls:
    - "CM-2 Baseline Configuration"
  pruneObjectBehavior: "DeleteIfCreated"
  remediationAction: enforce
  severity: medium
  namespace: global-policies
  orderPolicies: true
policies:
- name: policy-globalpolicy-namespace
  disabled: false
  manifests:
    - path: ./manifests-namespace
  policySets:
    - my-global-base-config
- name: policy-placementrules
  disabled: false
  manifests:
    - path: ./manifests-placementrules
  policySets:
    - my-global-hub-config
- name: policy-subscription-admin
  disabled: false
  manifests:
    - path: ./manifests-rbac
policySets:
  - name: my-global-hub-config
    placement:
      clusterSelectors:
        name: local-cluster
  - name: my-global-base-config
    placement:
      clusterSelectors: {}