apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: crossplane-subnet-2
spec:
  forProvider:
    cidrBlock: 10.0.2.0/24
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: provider-aws
