apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: crossplane-subnet-3
spec:
  forProvider:
    cidrBlock: 10.0.3.0/24
    vpcIdRef:
      name: crossplane-vpc
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: provider-aws
