apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: eks-cluster-1-placementrule
  namespace: stackrox
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchLabels:
      'name': 'eks-cluster-1'

