apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-aks-ingresscontroller
placementBindingDefaults:
  name: aks-ingresscontroller-pb
policyDefaults:
  namespace: global-policies
  # Use an existing placement rule so that placement bindings can be consolidated
  placement:
    placementRulePath: ../placementrules/aks-placementrule.yaml
  remediationAction: enforce
  severity: medium
policies:
- name: policy-aks-ingress
  disabled: false
  manifests:
    - path: ./manifests

