apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: non-local-ocp-placementrule.yaml
  namespace: global-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: NotIn
        values:
          - local-cluster
