apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-ingress
  namespace: tekton-pipelines
  annotations:
    nginx.org/rewrites: "serviceName=tekton-dashboard rewrite=/"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /tekton
        pathType: Prefix
        backend:
          service:
            name: tekton-dashboard
            port:
              number: 9097
