apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-ingress
  namespace: tekton-pipelines
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - '{{ (index (lookup "cluster.open-cluster-management.io/v1alpha1" "ClusterClaim" "" "name").spec.value) }}.{{hub (splitn "." 2 ((lookup "config.openshift.io/v1" "DNS" "" "cluster").spec.baseDomain | print) )._1 hub}}'
      secretName: tekton-ingress-cert
  rules:
  - host: '{{ (index (lookup "cluster.open-cluster-management.io/v1alpha1" "ClusterClaim" "" "name").spec.value) }}.{{hub (splitn "." 2 ((lookup "config.openshift.io/v1" "DNS" "" "cluster").spec.baseDomain | print) )._1 hub}}'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tekton-dashboard
            port:
              number: 9097
