apiVersion: v1
data:
  tls.crt: '{{hub fromSecret "openshift-service-ca" "signing-key" "tls.crt" hub}}'
  tls.key: '{{hub fromSecret "openshift-service-ca" "signing-key" "tls.key" hub}}'
kind: Secret
metadata:
  name: pki-key-pair
  namespace: openshift-cert-manager
type: Opaque