apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: ${EMAIL_ADDRESS}
    preferredChain: ''
    privateKeySecretRef:
      name: letsencrypt-secret
    server: 'https://acme-staging-v02.api.letsencrypt.org/directory'


