apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations: {}    
  labels:
    app: nginx-aks-controller
  name: nginx-subscription
  namespace: global-policies
spec:
  packageOverrides:
  - packageName: ingress-nginx
    packageAlias: ingress-nginx
    packageOverrides:
    - path: spec
      value:
        controller:
          setAsDefaultIngress: true
          replicaCount: "2"
          logLevel: "4"
          'service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path': "/healthz"
  placement:
    placementRef:
      kind: PlacementRule
      name: aks-placementrule