kind: Secret
apiVersion: v1
metadata:
  name: tekton-ingress-cert
  namespace: tekton-pipelines
  annotations:
    cert-manager.io/alt-names: '{{hub index (lookup "v1" "Secret" "kube-system" "tekton-ingress-cert").metadata.annotations "cert-manager.io/alt-names" hub}}'
    cert-manager.io/certificate-name: '{{hub index (lookup "v1" "Secret" "kube-system" "tekton-ingress-cert").metadata.annotations "cert-manager.io/certificate-name" hub}}'
    cert-manager.io/common-name: '{{hub index (lookup "v1" "Secret" "kube-system" "tekton-ingress-cert").metadata.annotations "cert-manager.io/common-name" hub}}'
    cert-manager.io/issuer-kind: '{{hub index (lookup "v1" "Secret" "kube-system" "tekton-ingress-cert").metadata.annotations "cert-manager.io/issuer-kind" hub}}'
    cert-manager.io/issuer-name: '{{hub index (lookup "v1" "Secret" "kube-system" "tekton-ingress-cert").metadata.annotations "cert-manager.io/issuer-name" hub}}'
    cert-manager.io/uri-sans: '{{hub index (lookup "v1" "Secret" "kube-system" "tekton-ingress-cert").metadata.annotations "cert-manager.io/uri-sans" hub}}'
    cert-manager.io/ip-sans: '{{hub index (lookup "v1" "Secret" "kube-system" "tekton-ingress-cert").metadata.annotations "cert-manager.io/ip-sans" hub}}'
data:
  tls.key: '{{hub fromSecret "kube-system" "tekton-ingress-cert" "tls.key" hub}}'
  tls.crt: '{{hub fromSecret "kube-system" "tekton-ingress-cert" "tls.crt" hub}}'
type: kubernetes.io/tls