apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: non-local-ocp-placementrule
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: NotIn
        values:
          - local-cluster
