apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-install-openshift-cert-manager-service-ca
placementBindingDefaults:
  name: openshift-operators-binding
policyDefaults:
  placement:
    placementRuleName: hub-placementrule
  controls:
    - "CM-2 Baseline Configuration"
  pruneObjectBehavior: "DeleteIfCreated"
  namespace: openshift-service-ca
  remediationAction: enforce
  severity: medium
policies:
  - name: policy-ocp-cert-service-ca
    manifests:
      - path: ./manifests

            