apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-xks-tekton
  labels:
    custom: tekton-xks-policy
placementBindingDefaults:
  name: xks-tekton-policy-pb
policyDefaults:
  namespace: global-policies
  # Use an existing placement rule so that placement bindings can be consolidated
  placement:
    placementRulePath: ../placementrules/non-openshift-placementrule.yaml
  remediationAction: enforce
  severity: medium
policies:
- name: policy-xks-tekton
  disabled: false
  manifests:
    - path: ./manifests
  remediationAction: enforce
