apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placementbinding-crossplane-eks-role-provider
  namespace: crossplane-system
placementRef:
  name: hub-placementrule
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-crossplane-eks-role-provider
    apiGroup: policy.open-cluster-management.io
    kind: Policy