#Source https://github.com/stolostron/policy-collection/blob/main/community/CM-Configuration-Management/policy-acs-operator-central.yaml
#Source https://github.com/redhat-cop/gitops-catalog/blob/main/advanced-cluster-security-operator/instance/base/central.yaml
apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  namespace: stackrox
  name: stackrox-central-services
spec:
  central:
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
  egress:
    connectivityPolicy: Online
  scanner:
    analyzer:
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 3
    scannerComponent: Enabled