#Source https://github.com/redhat-cop/gitops-catalog/blob/main/advanced-cluster-security-operator/instance/base/central.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-cluster-init
  namespace: stackrox
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - patch
      - update
  - apiGroups:
      - platform.stackrox.io
    resources:
      - securedclusters
    verbs:
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-cluster-init
  namespace: stackrox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-cluster-init
subjects:
  - kind: ServiceAccount
    name: create-cluster-init
    namespace: stackrox
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-cluster-init
  namespace: stackrox