apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: demo
    apps.open-cluster-management.io/git-path: crossplane/crossplane-resources/azure/manifests/overlays/region-eastus
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: crossplane-azure-resources
  name: azure-subscription-eastus
spec:
  channel: channel-git-crossplane/git-crossplane
  placement:
    placementRef:
      kind: PlacementRule
      name: hub-placementrule
