resources:
- application.yaml
- channel.yaml
- subscription.yaml
- namespace-stackrox.yaml
- hub-placementrule.yaml
- policy-configure-subscription-admin-hub
- rolebinding-argocd-application-controller.yaml
- rolebinding-argocd-redis.yaml
- rolebinding-argocd-stackrox.yaml
- rolebinding-openshift-gitops-argocd-server.yaml


