apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-configure-acs-central-details
  namespace: global-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-configure-acs-central-details
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: ConfigMap
                apiVersion: v1
                metadata:
                  name: central-config-details
                  namespace: global-policies
                  labels:
                    app: stackrox-enrollment
                data:
                  provision-url: |
                    {{hub (lookup "route.openshift.io/v1" "Route" "global-policies" "el-secured-cluster-tekton-task").spec.host hub}}                           
                  image-url: |
                    {{hub range $element :=((lookup "route.openshift.io/v1" "Route" "global-policies" "el-secured-cluster-tekton-task").spec.host) hub}}                           
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-configure-acs-central-details
placementRef:
  name: placement-policy-configure-acs-central-details
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-configure-acs-central-details
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-configure-acs-central-details
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: name, operator: NotIn, values: ["local-cluster"]}