bases:
#ACM Attach Cluster Files
- ../../../policy-acm-cluster-attach
- ../../../job-acm-cluster-attach/aks
namespace: crossplane-system
patchesJson6902:
  - target:
      group: batch
      version: v1
      kind: Job
      name: until-cluster-ready
    path: ./patches/job-patch.yaml
  - target:
      group: policy.open-cluster-management.io
      version: v1
      kind: Policy
      name: policy-replace-me
    path: ./patches/policy-patch.yaml
  - target:
      group: policy.open-cluster-management.io
      version: v1
      kind: Policy
      name: policy-secret-replace-me
    path: ./patches/policy-secret-patch.yaml
  - target:
      group: policy.open-cluster-management.io
      version: v1
      kind: PlacementBinding
      name: pb-replace-me
    path: ./patches/pb-patch.yaml