
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: crossplane-subnet-1
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1a
    vpcIdRef:
      name: crossplane-vpc-us-east-1
#Tagged for eks-cluster-1 usage
    tags:
      - key: kubernetes.io/cluster/eks-cluster-1
        value: ""
      - key: kubernetes.io/role/elb
        value: ""