apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placementbinding-crossplane-sub-lb-helm
  namespace: crossplane-system
placementRef:
  name: hub-placementrule
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-crossplane-crossplane-sub-lb-helm
    apiGroup: policy.open-cluster-management.io
    kind: Policy