apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: clustername-placementrule
  namespace: kube-system
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchLabels:
      name: clustername