apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: non-local-ocp-placement
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: NotIn
              values:
                - local-cluster