apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policygeneratorcrossplane
placementBindingDefaults:
  name: crossplane-install-binding
policyDefaults:
  placement:
    placementRuleName: hub-placementrule
  controls:
    - "CM-2 Baseline Configuration"
  pruneObjectBehavior: "DeleteIfCreated"
  namespace: global-policies
  remediationAction: enforce
  severity: medium
policies:
- name: policy-crossplane-helm-repo
  disabled: false
  manifests:
    - path: ./crossplane-helm-repo
- name: policy-crossplane-git-repo
  disabled: false
  manifests:
    - path: ./crossplane-git-repo
- name: policy-crossplane-app-install
  disabled: false
  manifests:
    - path: ./crossplane-install-non-vault
- name: policy-crossplane-providers
  disabled: false
  manifests:
    - path: ./crossplane-provider

    
