apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  labels:
    app: crossplane
  name: git-crossplane-cluster
  namespace: channel-git-crossplane-cluster
spec:
  pathname: https://github.com/MoOyeg/rhacm-multi-kubernetes-example.git
  type: Git