---
apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSCluster
metadata:
  name: crossplane-aks-cluster1
  labels:
    app: "crossplane"
    provider: azure
spec: 
  disableRBAC: false
  providerConfigRef:
    name: crossplane-azure

