apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd-operator
spec:
  server:
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    insecure: true
