bases:
- ../../../base/subscription
patches:
  - path: ./patches/patch-policy-subscription.yaml
    target:
      kind: Policy
  - path: ./patches/patch-placementbinding-subscription.yaml
    target:
      kind: PlacementBinding
  - path: ./patches/patch-placementrule.yaml
    target:
      kind: PlacementRule
patchesJson6902:
  - target:
      group: policy.open-cluster-management.io
      version: v1
      kind: Policy
      name: policy-crossplane-sub-lb-helm
    path: ./patches/patch-policy-subscription-rename.yaml
  - target:
      group: policy.open-cluster-management.io
      version: v1
      kind: PlacementBinding
      name: placementbinding-crossplane-eks-lb-sa
    path: ./patches/patch-placementbinding-subscription-rename.yaml
  - target:
      group: apps.open-cluster-management.io
      version: v1
      kind: PlacementRule
      name: clustername-placementrule
    path: ./patches/patch-placementrule-rename.yaml