apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-eks-nginx-ingresscontroller
placementBindingDefaults:
  name: eks-nginx-ingresscontroller
policyDefaults:
  namespace: global-policies
  # Use an existing placement rule so that placement bindings can be consolidated
  placement:
    placementRuleName: hub-placementrule
  remediationAction: enforce
  severity: medium
  pruneObjectBehavior: "DeleteIfCreated"
policies:
- name: policy-eks-nginx-ingress-app
  disabled: false
  manifests:
    - path: ./eks-base
