#Source: https://github.com/renatoppuccini/demo-acm-acs-eks/blob/main/policies/acs-securedcluster/policy.yaml
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations: null
  labels:
    app: stackrox-secured-cluster-services
  name: stackrox-secured-cluster-services-managedcluster-replace-me
  namespace: stackrox
spec:
  channel: channel-helm-rhacs/rhacs-charts
  placement:
    placementRef:
      kind: PlacementRule
      name: managedcluster-replace-me-placementrule
  name: stackrox-secured-cluster-services
  packageOverrides:
  - packageAlias: stackrox-secured-cluster-svcs
    packageName: stackrox-secured-cluster-services
    packageOverrides:
    - path: spec
      value:
        admissionControl:
          serviceTLS:
            cert: |
              {{hub (index (lookup "v1" "Secret" "stackrox"
              "admission-control-tls").data
              "admission-control-cert.pem") | base64dec |
              indent 18 hub}}
            key: |
              {{hub (index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "admission-control-key.pem") | base64dec | indent 18 hub}}
        allowNonstandardReleaseName: true
        ca:
          cert: |
            {{hub (index (lookup "v1" "Secret" "stackrox" "admission-control-tls").data "ca.pem") | base64dec | indent 16 hub}}
        centralEndpoint: '{{hub (lookup "route.openshift.io/v1" "Route"
          "stackrox" "central").spec.host hub}}:443'
        clusterName: managedcluster-replace-me
        collector:
          serviceTLS:
            cert: |
              {{hub (index (lookup "v1" "Secret" "stackrox" "collector-tls").data "collector-cert.pem") | base64dec | indent 18 hub}}
            key: |
              {{hub (index (lookup "v1" "Secret" "stackrox" "collector-tls").data "collector-key.pem") | base64dec | indent 18 hub}}
        imagePullSecrets: 
          useExisting: pull-secret
        sensor:
          serviceTLS:
            cert: |
              {{hub (index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "sensor-cert.pem") | base64dec | indent 18 hub}}
            key:  | 
              {{hub (index (lookup "v1" "Secret" "stackrox" "sensor-tls").data "sensor-key.pem") | base64dec | indent 18 hub}}

