apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: pacman-app
  name: pacman-placementrule-all
  namespace: pacman-app
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - pacman-app