apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placementbinding-crossplane-sub-lb-helm
placementRef:
  name: hub-placementrule
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-sub-lb-helm-eks-cluster-1
    apiGroup: policy.open-cluster-management.io
    kind: Policy