kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage
  namespace: pacman-app
  labels:
    app.kubernetes.io/name: pacman
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
