apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: pacman-app
  name: pacman
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: pacman
              servicePort: 80