kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhacs-stackrox-gitops-role
  namespace: stackrox
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
    apiGroups:
      - platform.stackrox.io
    resources:
      - centrals
      - securedclusters