apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-xks-olm
policyDefaults:
  policySets:
    - global-xks-policies
  namespace: global-policies
  controls:
    - "CM-2 Baseline Configuration"
  pruneObjectBehavior: "DeleteIfCreated"
  remediationAction: enforce
  severity: medium
policies:
- name: policy-xks-olm-crds
  disabled: false
  manifests:
    - path: ./crds
- name: policy-xks-olm-deploy
  disabled: false
  manifests:
    - path: ./olm_deploy
  remediationAction: enforce
policySets:
  - name: global-xks-policies
    placement: 
