apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: demo2
    apps.open-cluster-management.io/git-path: placementrules
  labels:
    app: app-placementrules
  name: app-placmentrules-sub
  namespace: global-policies
spec:
  channel: channel-rhacm-git-ns/rhacm-git
  placement:
    placementRef:
      kind: PlacementRule
      name: bootstrap-hub-placementrule


