apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: demo2
    apps.open-cluster-management.io/git-path: crossplane/crossplane-clusters/manifests/aks-cluster-overlays/crossplane-aks-cluster1/cluster-create 
  labels:
    app: crossplane-clusters
  name: crossplane-cluster-aks-cluster-1
  namespace: crossplane-system
spec:
  channel: channel-git-crossplane/git-crossplane
  placement:
    placementRef:
      kind: PlacementRule
      name: hub-placementrule
