#Source https://github.com/stolostron/policy-collection/blob/main/community/CM-Configuration-Management/policy-acs-operator-central.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhacs-operator-group
  namespace: rhacs-operator
spec:
  upgradeStrategy: Default

