apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  labels:
    app: metadata-app
  name: channel-k8s-metadata-app
  namespace: metadata-app
spec:
  pathname: https://github.com/MoOyeg/rhacm-multi-kubernetes-example.git
  type: Git