apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: non-ocp-placementrule-metadata-app
  namespace: metadata-app
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - AKS
          - EKS
          - GKS
      - key: app
        operator: In
        values:
          - metadata-app