apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: ocp-placementrule-metadata-app
  namespace: metadata-service
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
      - key: app
        operator: In
        values:
          - metadata-app