apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: demo3
    apps.open-cluster-management.io/git-path: metadata-app/argo-application/overlays/xks
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: metadata-app
  name: metadata-subscription-non-ocp
  namespace: metadata-acm-app
spec:
  channel: metadata-acm-app/channel-k8s-metadata-app
  placement:
    placementRef:
      kind: PlacementRule
      name: non-ocp-placementrule-metadata-app
