apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pacman
    app.kubernetes.io/name: pacman
  name: pacman
  namespace: pacman-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pacman
      app.kubernetes.io/name: pacman
  template:
    metadata:
      labels:
        name: pacman
        app.kubernetes.io/name: pacman
    spec:
      containers:
      - image: quay.io/mooyeg/pacman:1.0
        name: pacman
        ports:
        - containerPort: 8080
          name: http-server
        env:
          - name: METADATA_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: METADATA_NODE_PORT
            value: '16261'
