apiVersion: batch/v1
kind: Job
metadata:
  name: until-cluster-ready
  namespace: crossplane-system
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          env:
            - name: SECRETNAME
              value: replace-me
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash
              
              count=60

              until oc get secret/${SECRETNAME} -o name -n crossplane-system
              do
              count=$((count-1))
              echo "Sleep for 60 seconds, Will check for secret - $count more times"
              sleep 60
              if [ $count -le 0 ]
              then
                echo "We couldnt find secret ${SECRETNAME}"                
                break
              fi
              done

              #When Our xKS cluster secret is available we can create our auto import secret from it
              oc patch policy/policy-secret-attach-${SECRETNAME} -n crossplane-system -p '{"spec":{"disabled":false}}' --type=merge
              
              count=50
              until oc get policy/policy-secret-attach-${SECRETNAME}  -n crossplane-system -o jsonpath='{.status.compliant}'
              do
              count=$((count-1))
              echo "Sleep for 60 seconds, Will check auto-import secret policy $count more times"
              sleep 60
              if [ $count -le 0 ]
              then
                echo "Policy not validated for Policy ${SECRETNAME}"
                break
              fi
              done

              #Enable our ManagedClusterPolicy
              oc patch policy/policy-attach-${SECRETNAME} -n crossplane-system -p '{"spec":{"disabled":false}}' --type=merge

              #Delete our Import Secret Policy - ACM will delete the auto-import-secret we create
              oc delete policy/policy-secret-attach-${SECRETNAME} -n crossplane-system
              

          imagePullPolicy: Always
          name: until-cluster-ready
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccountName: crossplane
      serviceAccount: crossplane