---
apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSCluster
metadata:
  name: aks-cluster-1
  labels:
    app: "crossplane"
    provider: azure
spec: 
  resourceGroupName: openenv-5cd6x
  #resourceGroupNameRef:
  #  name: openenv-5cd6x
  vnetSubnetIDRef:
    name: crossplane-azure-subnet-eastus
  location: East US
  version: "1.26.0"
  nodeCount: 3
  nodeVMSize: Standard_D8s_v3
  dnsNamePrefix: aks-cluster-1
  disableRBAC: false
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: aks-cluster-1
