apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metadata-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: pacman-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: demo-subscription-gitops/cloud-provider/nginx/
    repoURL: https://github.com/stolostron/demo-subscription-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""