#Some Research is required copying this cert
#The Secret should be auto-rotated by cert-manager but the template that ACM uses is only templated once on the hub(its continuosly done on managedclusters)
kind: Secret
apiVersion: v1
metadata:
  name: ocp-acme-wildcard-cert-secret
  namespace: openshift-ingress
  annotations:
    cert-manager.io/alt-names: '{{ index (lookup "v1" "Secret" "kube-system" "ocp-acme-wildcard-cert-secret").metadata.annotations "cert-manager.io/alt-names" }}'
    cert-manager.io/certificate-name: '{{ index (lookup "v1" "Secret" "kube-system" "ocp-acme-wildcard-cert-secret").metadata.annotations "cert-manager.io/certificate-name" }}'
    cert-manager.io/common-name: '{{ index (lookup "v1" "Secret" "kube-system" "ocp-acme-wildcard-cert-secret").metadata.annotations "cert-manager.io/common-name" }}'
    cert-manager.io/issuer-kind: '{{ index (lookup "v1" "Secret" "kube-system" "ocp-acme-wildcard-cert-secret").metadata.annotations "cert-manager.io/issuer-kind" }}'
    cert-manager.io/issuer-name: '{{ index (lookup "v1" "Secret" "kube-system" "ocp-acme-wildcard-cert-secret").metadata.annotations "cert-manager.io/issuer-name" }}'
    cert-manager.io/uri-sans: '{{ index (lookup "v1" "Secret" "kube-system" "ocp-acme-wildcard-cert-secret").metadata.annotations "cert-manager.io/uri-sans" }}'
    cert-manager.io/ip-sans: '{{ index (lookup "v1" "Secret" "kube-system" "ocp-acme-wildcard-cert-secret").metadata.annotations "cert-manager.io/ip-sans" }}'
data:
  tls.key: '{{ fromSecret "kube-system" "ocp-acme-wildcard-cert-secret" "tls.key" }}'
  tls.crt: '{{ fromSecret "kube-system" "ocp-acme-wildcard-cert-secret" "tls.crt" }}'
type: kubernetes.io/tls