apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: crossplane-routetable-2
spec:
  forProvider:
    region: us-east-2
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: crossplane-ig-us-east-2
    associations:
      - subnetIdRef:
          name: crossplane-subnet-2-us-east-2
    vpcIdRef:
      name: crossplane-vpc-us-east-2
