apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "selfsigned-ca-{{hub .ManagedClusterName hub}}"
  namespace: cert-manager
spec:
  isCA: true
  commonName: "selfsigned-ca-{{hub .ManagedClusterName hub}}"
  secretName: "secret-{{hub .ManagedClusterName hub}}"
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: "issuer-{{hub .ManagedClusterName hub}}"
    kind: ClusterIssuer
    group: cert-manager.io