apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ocp-acme-wildcard-cert
  namespace: kube-system
  labels:
    use-dns-solver: "true"
spec:
  secretName: ocp-acme-wildcard-cert-secret
  duration: 24h
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-staging
  commonName: '*.apps.{{ (lookup "config.openshift.io/v1" "DNS" "" "cluster").spec.baseDomain }}'
  dnsNames:
    - '*.apps.{{ (lookup "config.openshift.io/v1" "DNS" "" "cluster").spec.baseDomain }}'
    - '*.{{ (lookup "config.openshift.io/v1" "DNS" "" "cluster").spec.baseDomain }}'