apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesJson6902:
- patch: |-
    - op: replace
      path: /kind
      value: Application
    - op: add
      path: /metadata/namespace
      value: 
        metadata-app
    - op: add
      path: /spec/source/path
      value: 
        gitops/overlays/base    
  target:
    group: argoproj.io
    kind: Application
    name: metadata-app
    version: v1alpha1
bases:
 - ../../base
resources:
 - argocd-instance.yaml
namespace: metadata-app