apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metadata-argo-app
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/base/
    repoURL: https://github.com/MoOyeg/kubernetes-cloud-metadata-tool.git
    targetRevision: working
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""