apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: amazon-placementrule
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: cloud
        operator: In
        values:
          - Amazon
