apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations: {}    
  labels:
    app: nginx-eks-controller
  name: nginx-subscription
  namespace: global-policies
spec:
  packageOverrides:
  - packageName: ingress-nginx
    packageAlias: ingress-nginx
    packageOverrides:
    - path: spec
      value:
        controller.replicaCount: "2"
        controller.service.annotations.service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: '/healthz'
  placement:
    placementRef:
      kind: PlacementRule
      name: eks-placementrule