apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infra-pipeline 
  namespace: global-policies
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: global-policies