apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: automation
  namespace: ansible-automation-platform
spec:
  admin_user: admin
  create_preload_data: true
  garbage_collect_secrets: false
  image_pull_policy: IfNotPresent
  loadbalancer_port: 80
  loadbalancer_protocol: http
  nodeport_port: 30080
  projects_persistence: false
  projects_storage_access_mode: ReadWriteMany
  projects_storage_size: 8Gi
  replicas: 1
  route_tls_termination_mechanism: Edge
  task_privileged: false