#Policy Changes
- op: replace
  path: /metadata/name
  value: policy-attach-eks-cluster-1
- op: replace
  path: /spec/policy-templates/0/objectDefinition/metadata/name
  value: policy-attach-eks-cluster-1
- op: replace
  path: /spec/disabled
  value: '{{ ne (lookup "policy.open-cluster-management.io/v1" "Policy" "crossplane-system" "policy-attach-eks-cluster-1").status.compliant "Compliant" |  print | toBool }}'
#ManagedCluster Object Changes
- op: replace
  path: /spec/policy-templates/0/objectDefinition/spec/object-templates/0/objectDefinition/metadata/name
  value: eks-cluster-1
#KlusterletAddonConfig Object Changes
- op: replace
  path: /spec/policy-templates/0/objectDefinition/spec/object-templates/1/objectDefinition/metadata/name
  value: eks-cluster-1
- op: replace
  path: /spec/policy-templates/0/objectDefinition/spec/object-templates/1/objectDefinition/metadata/namespace
  value: eks-cluster-1
- op: replace
  path: /spec/policy-templates/0/objectDefinition/spec/object-templates/1/objectDefinition/spec/clusterName
  value: eks-cluster-1
- op: replace
  path: /spec/policy-templates/0/objectDefinition/spec/object-templates/1/objectDefinition/spec/clusterNamespace
  value: eks-cluster-1