---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: stackrox-enrollment-channel
  namespace: stackrox-enrollment
spec:
  type: Namespace
  pathname: stackrox-enrollment
  sourceNamespaces:
    - stackrox-enrollment