apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: secured-cluster-pipeline-template
  namespace: global-policies
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: secured-cluster-pipelinerun-
        labels:
          tekton.dev/pipeline: secured-cluster-tekton-pipeline
      spec:
        pipelineRef:
          name: secured-cluster-tekton-pipeline
        serviceAccountName: 'infra-pipeline'